# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/Globomantics.Data.sln'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/**Tests.csproj'
    testRunTitle: 'Test'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '--collect "Code coverage"'
- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'
    projectName: 'Whitesource Scan'