# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/Globomantics.Data.sln'
- task: CmdLine@2
  inputs:
    script: 'dotnet nuget push $(Build.Repository.LocalPath)/OurWebApp.Data/bin/Debug/*.nupkg --source https://nuget.pkg.github.com/FeynmanFan/index.json --api-key $(GITHUBAPIKEY)'